AllCops:
  TargetRubyVersion: 2.1
  Exclude:
    - _site/**/*
    - vendor/**/*

Metrics/LineLength:
  Enabled: false

Metrics/MethodLength:
  Enabled: false

Metrics/AbcSize:
  Enabled: false

Style/Documentation:
  Enabled: false
